export const TZ = "TZ";
export const API_PORT = "API_PORT";
export const LOGGING_LEVEL = "LOGGING_LEVEL";

export const HUE_ADDRESS = "HUE_ADDRESS";
export const HUE_USERNAME = "HUE_USERNAME";
export const HUE_SENSOR_IDS = "HUE_SENSOR_IDS";

export const REACTION_TIMEOUT_SECONDS = "REACTION_TIMEOUT_SECONDS";
export const REACTION_CHECK_INTERVAL_MILLISECONDS =
  "REACTION_CHECK_INTERVAL_MILLISECONDS";
export const REACTION_FORCE_OCCASIONAL_PLAY = "REACTION_FORCE_OCCASIONAL_PLAY";